import Link from "next/link";
import { ArrowLeft, Sparkles } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";
import { PageHeader } from "@/components/admin/page-header";
import { CampaignComposer } from "@/components/admin/campaign-composer";
import { Alert } from "@/components/ui/misc";
import type { PromoCode } from "@/lib/types/database";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;

function str(v: string | string[] | undefined): string {
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}

export default async function NewCampaignPage({
  searchParams,
}: {
  searchParams: SearchParams;
}) {
  const sp = await searchParams;
  let promos: PromoCode[] = [];
  let eligibleCount = 0;
  let configError = false;

  try {
    const admin = createAdminClient();
    const [promoRes, customerCountRes] = await Promise.all([
      admin
        .from("promo_codes")
        .select("*")
        .eq("is_active", true)
        .order("code"),
      admin
        .from("customers")
        .select("id", { count: "exact", head: true })
        .not("email", "is", null)
        .eq("marketing_opted_out", false)
        .eq("is_blacklisted", false),
    ]);
    promos = (promoRes.data as PromoCode[]) ?? [];
    eligibleCount = customerCountRes.count ?? 0;
  } catch {
    configError = true;
  }

  // Prefill from the AI suggestion flow on /admin/marketing.
  const prefill = {
    name: str(sp.name),
    subject: str(sp.subject),
    preheader: str(sp.preheader),
    body: str(sp.body),
    suggested_promo_code: str(sp.promo_code),
    suggested_discount_percent: Number(str(sp.discount_percent)) || 0,
    holiday: str(sp.holiday),
  };
  const isPrefilled = Boolean(prefill.subject && prefill.body);

  // If the AI suggested a promo code that matches one of our active codes,
  // pre-select it. Otherwise leave the dropdown empty — the operator can
  // create the code separately and come back, or just send without one.
  const matchingPromo =
    isPrefilled && prefill.suggested_promo_code
      ? promos.find(
          (p) => p.code.toUpperCase() === prefill.suggested_promo_code,
        )
      : null;

  return (
    <>
      <Link
        href="/admin/marketing"
        className="mb-3 inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 hover:text-gold-600"
      >
        <ArrowLeft className="h-4 w-4" /> Back to Marketing
      </Link>
      <PageHeader
        title={isPrefilled ? "New Campaign (AI Draft)" : "New Campaign"}
        subtitle={
          isPrefilled
            ? "AI-generated draft — edit anything before sending."
            : "Compose a branded promotional email and send it to every eligible customer."
        }
      />

      {/* AI prefill notice — shown only when the form was opened from the
          holiday suggestions flow. Calls out the suggested promo code so
          the operator can create it in a new tab if needed. */}
      {isPrefilled && (
        <div className="mb-6 rounded-xl border border-gold-200 bg-gold-50/50 p-4 text-sm text-gold-900">
          <p className="flex items-center gap-1.5 font-semibold">
            <Sparkles className="h-4 w-4 text-gold-600" />
            AI draft ready
          </p>
          <p className="mt-1 text-xs">
            All fields below were generated by AI. Edit anything you like
            before sending.
            {prefill.suggested_promo_code && !matchingPromo && (
              <>
                {" "}
                Suggested promo code:{" "}
                <strong className="font-mono">
                  {prefill.suggested_promo_code}
                </strong>{" "}
                ({prefill.suggested_discount_percent}% off) —{" "}
                <a
                  href="/admin/promo-codes"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline hover:text-gold-700"
                >
                  create it
                </a>{" "}
                in a new tab if you want to attach it.
              </>
            )}
            {matchingPromo && (
              <>
                {" "}
                Promo code{" "}
                <strong className="font-mono">{matchingPromo.code}</strong>{" "}
                was matched + pre-selected below.
              </>
            )}
          </p>
        </div>
      )}

      {configError ? (
        <Alert tone="warning">
          Could not load promo codes. Run migration 0028 in Supabase.
        </Alert>
      ) : (
        <CampaignComposer
          promos={promos}
          eligibleCount={eligibleCount}
          initial={{
            name: prefill.name,
            subject: prefill.subject,
            preheader: prefill.preheader,
            body: prefill.body,
            promo_code_id: matchingPromo?.id ?? "",
          }}
        />
      )}
    </>
  );
}
