"use client";

import { useState, useRef, useEffect } from "react";
import { Sparkles, Send, Loader2 } from "lucide-react";
import { Card, CardBody } from "@/components/ui/card";
import { askBusinessQuestion } from "@/app/admin/(panel)/ask/actions";

interface Msg {
  role: "user" | "assistant";
  content: string;
}

const SUGGESTIONS = [
  "How much revenue did we make this month?",
  "Which vehicle has earned the most?",
  "How many cars are available right now?",
  "What's our total outstanding balance?",
  "How many pickups are coming up this week?",
];

export function AskAssistant() {
  const [messages, setMessages] = useState<Msg[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({
      top: scrollRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages, loading]);

  async function ask(text: string) {
    const q = text.trim();
    if (!q || loading) return;
    setError(null);
    const next: Msg[] = [...messages, { role: "user", content: q }];
    setMessages(next);
    setInput("");
    setLoading(true);
    try {
      const res = await askBusinessQuestion(next);
      if (res.ok && res.answer) {
        setMessages((m) => [...m, { role: "assistant", content: res.answer! }]);
      } else {
        throw new Error(res.error ?? "Could not answer that.");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not answer that.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card>
      <CardBody className="space-y-4">
        <div
          ref={scrollRef}
          className="max-h-[55vh] min-h-[180px] space-y-3 overflow-y-auto"
        >
          {messages.length === 0 && (
            <div className="space-y-3 py-4 text-center">
              <span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-gold-100 text-gold-600">
                <Sparkles className="h-6 w-6" />
              </span>
              <p className="text-sm text-slate-500">
                Ask a question about your business — revenue, fleet, bookings
                and more.
              </p>
            </div>
          )}
          {messages.map((m, i) => (
            <div
              key={i}
              className={m.role === "user" ? "flex justify-end" : "flex justify-start"}
            >
              <div
                className={
                  m.role === "user"
                    ? "max-w-[80%] rounded-2xl rounded-br-sm bg-slate-900 px-3.5 py-2 text-sm text-white"
                    : "max-w-[85%] whitespace-pre-line rounded-2xl rounded-bl-sm border border-slate-200 bg-slate-50 px-3.5 py-2 text-sm text-slate-700"
                }
              >
                {m.content}
              </div>
            </div>
          ))}
          {loading && (
            <div className="flex items-center gap-2 text-xs text-slate-400">
              <Loader2 className="h-3.5 w-3.5 animate-spin" /> Checking your
              numbers…
            </div>
          )}
        </div>

        {error && <p className="text-sm text-rose-600">{error}</p>}

        {messages.length === 0 && (
          <div className="flex flex-wrap gap-2">
            {SUGGESTIONS.map((s) => (
              <button
                key={s}
                onClick={() => ask(s)}
                className="rounded-full border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-600 transition-colors hover:border-gold-400 hover:text-slate-900"
              >
                {s}
              </button>
            ))}
          </div>
        )}

        <form
          onSubmit={(e) => {
            e.preventDefault();
            ask(input);
          }}
          className="flex items-center gap-2 border-t border-slate-100 pt-4"
        >
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask about revenue, bookings, your fleet…"
            className="h-11 flex-1 rounded-lg border border-slate-300 px-3 text-sm text-slate-800 placeholder:text-slate-400 focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-400/25"
          />
          <button
            type="submit"
            disabled={loading || !input.trim()}
            aria-label="Ask"
            className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-gold-500 text-brand-950 transition-colors hover:bg-gold-400 disabled:opacity-50"
          >
            <Send className="h-4 w-4" />
          </button>
        </form>
        <p className="text-[11px] text-slate-400">
          Answers are generated by AI from your live data and may not be
          perfect — double-check important figures in the Reports section.
        </p>
      </CardBody>
    </Card>
  );
}
