-- ============================================================================
-- Car Mart Rentals
-- Migration 0010: Replace the default rental agreement with the company's
-- ARRC California Rental Agreement Terms and Conditions.
--
-- Updates the existing default template. Agreements are snapshotted at
-- check-out, so already-signed agreements keep their original terms.
-- ============================================================================

update agreement_templates
set name     = 'Rental Agreement Terms and Conditions',
    sections = $cmr_terms$
[
  {
    "title": "Definitions",
    "body": "\"Agreement\" means all terms and conditions found in the Rental Agreement, vehicle inspection form, these Terms and Conditions, any addenda and any additional documents you sign or we provide at the time of rental. \"You\" or \"your\" means the person identified as the renter in this Agreement, each person signing this Agreement, each Authorized Driver, and every person or organization to whom charges are billed by us at its or the renter's direction. All persons referred to as \"you\" or \"your\" are jointly and severally bound by this Agreement. \"We,\" \"our,\" or \"us\" means the independent rental company named elsewhere in this Agreement. \"Authorized Driver\" means (a) the renter and the renter's spouse; (b) the renter's employer or co-worker if engaged in business activity with the renter; and (c) any additional driver listed by us on this Agreement. Each Authorized Driver must have a valid driver's license and be at least 21 years of age. Only Authorized Drivers are permitted to use the Vehicle. \"Vehicle\" means the automobile or truck identified in this Agreement and any vehicle we substitute for it, and all its tires, tools, accessories, equipment, keys and Vehicle documents. \"CDW\" means Collision Damage Waiver. \"TWWD\" means Tire, Wheel, and Windshield Damage Waiver. \"Charges\" means the fees and charges incurred under this Agreement. All amounts expressed under this Agreement shall be payable in U.S. dollars. \"Rental Period\" means the period between the time that you take possession of the Vehicle and the time that the Vehicle is either returned to or recovered by us and checked in by us. \"Additional Mandatory Charges\" means customer facility charges, airport concession recovery fees, tourism commission fees, vehicle license recovery fees, or other government-imposed tax or fee. \"Vehicle License Recovery Fee\" means a charge to recover vehicle license and vehicle registration fees as permitted under California law."
  },
  {
    "title": "Nature of Rental; Condition and Return of Vehicle",
    "body": "This is a contract for the rental of the Vehicle only. You do not have the right to sublease the Vehicle. You must return the Vehicle to our rental office or other location we specify, on the date and time noted in this Agreement (or sooner upon our demand) and in the same condition that you received it except for ordinary wear. To extend the Rental Period, you must first obtain our approval by contacting our rental office before the due-in date. If the Vehicle is returned after closing hours, you remain responsible for all loss of or damage to the Vehicle until we inspect it upon our next opening for business (regardless of when such loss or damage occurred), and Charges may continue to accrue until that time. Service to the Vehicle or replacement of parts or accessories during the Rental Period must have our prior written approval. You must check and maintain all fluid levels, and return the Vehicle with at least the same amount of fuel as when rented unless you purchase a prepaid fuel option. To the extent permitted by law, we may repossess the Vehicle at your expense without notice to you, if the Vehicle is abandoned or used in violation of law or this Agreement."
  },
  {
    "title": "Indemnity; No Warranties",
    "body": "To the fullest extent permitted by law: (a) you agree to indemnify us, defend us and hold us harmless from all judgments, claims, liability, costs and attorney fees we incur resulting from, or arising out of, this rental, your use of the Vehicle or our repossession of it, and/or your use of optional equipment (\"Optional Equipment\"); and (b) we make no warranties, express, implied or apparent, regarding the Vehicle or Optional Equipment that we rent to you for use in the vehicle, no warranty of merchantability and no warranty that the Vehicle or Optional Equipment is fit for a particular purpose."
  },
  {
    "title": "Responsibility for Damage or Loss",
    "body": "You are responsible for all damage to or loss of the Vehicle caused by collision, regardless of fault. Subject to limits of California law, your responsibility includes: (a) all physical and mechanical damage to the Vehicle measured as follows: (i) if we determine that the Vehicle is a total loss, the fair market value of the Vehicle less salvage; (ii) if we determine that the Vehicle is repairable, the actual or estimated cost of the repairs performed; (b) an administrative fee; and (c) our actual charges for towing, storage, and impound. You are responsible for loss due to theft of the Vehicle and damage caused by vandalism that occurs in connection with a theft if you fail to exercise ordinary care while in possession of the Vehicle. You are responsible for damage due to vandalism not associated with theft of the Vehicle up to a maximum of $500. You are responsible for replacing missing equipment and Vehicle documents and keys. You must report all Vehicle accidents and incidents of theft or vandalism to us and the police upon discovery."
  },
  {
    "title": "Prohibited Use of the Vehicle",
    "body": "Certain uses of the Vehicle and other actions by you or another driver or a passenger are prohibited uses (\"Prohibited Uses\"). The following are Prohibited Uses of the Vehicle: (a) by anyone who (i) is not an Authorized Driver, or whose driving license is suspended in any jurisdiction; (ii) is under the influence of a prescription or non-prescription drug, controlled substance, or alcohol; or (iii) lacks experience operating a manual transmission if applicable; (b) in furtherance of any illegal purpose or under any circumstance that would constitute a felony or other violation of law (other than a minor traffic violation); (c) to carry persons or property for hire; (d) to push or tow anything, to teach anyone to drive, or to carry objects on the roof of the Vehicle; (e) in any race, speed test or contest; (f) to carry dangerous or hazardous items or illegal materiel; (g) outside the United States, Canada, or the geographic area described elsewhere in this Agreement; (h) when loaded beyond its capacity as determined by the manufacturer of the Vehicle; (i) on unpaved surfaces; (j) to transport more persons than the Vehicle has seat belts, or to carry persons outside the passenger compartment; (k) to transport children without approved child safety seats as required by law; (l) when the odometer has been tampered with or disconnected; (m) when the Vehicle's fluid levels are low, or it is otherwise reasonable to expect you to know that further operation would damage the Vehicle; (n) with inadequately secured cargo; (o) after an accident with the Vehicle unless and until you summon the police to the accident scene; (p) to transport an animal (other than a service animal); (q) in or through any structure or underpass where there is insufficient clearance (width or height); (r) by anyone who is driving or operating the Vehicle while using a hand-held wireless communication device or other device that is capable of receiving or transmitting telephonic communications, electronic data, mail or text messages while not in a hands-free mode; or (s) in a reckless manner or with willful or intentional disregard to the Vehicle or to third parties and their property. The following are also Prohibited Uses: failure to notify us and the police of an accident, theft, or vandalism involving the Vehicle; providing false, misleading or fraudulent information to us or withholding information that would have caused us not to rent the Vehicle; and smoking or vaping any substance in the Vehicle. PROHIBITED USE OF THE VEHICLE VIOLATES THIS AGREEMENT, AUTOMATICALLY TERMINATES YOUR RENTAL, AND VOIDS ALL LIABILITY AND OTHER INSURANCE COVERAGE (TO THE EXTENT PERMITTED BY LAW)."
  },
  {
    "title": "Collision Damage Waiver",
    "body": "If we offer, and you purchase, CDW, we will waive our right to hold you financially responsible for damage to or loss of the Vehicle. CDW is not insurance, is optional, and may duplicate coverage under your own insurance policy or credit card. CDW does not apply to Optional Equipment. Your CDW will be invalidated, and we will not waive our right to hold you financially responsible for loss of or damage to the Vehicle: (a) if you provided fraudulent information to us or if you provided false information to us and we would not have rented the Vehicle had we received true information; (b) if damage to or loss of the Vehicle results from: (i) your intentional, willful, wanton, or reckless conduct; (ii) operation of the Vehicle under the influence of drugs or alcohol in violation of Section 23152 of the California Vehicle Code; (iii) towing or pushing anything; or (iv) operation of the Vehicle on an unpaved road if the damage or loss is a direct result of the road or driving conditions; or (c) if damage to or loss of the Vehicle occurs while the Vehicle is: (i) used for commercial hire; (ii) used in connection with conduct that could be properly charged as a felony; (iii) involved in a speed test, contest, or driver training activity; (iv) operated by a person other than an Authorized Driver; or (v) operated outside the United States."
  },
  {
    "title": "Optional Equipment",
    "body": "We offer certain Optional Equipment, including navigational systems and child safety seats, upon request and subject to availability for your use during the Rental Period at an additional charge. All Optional Equipment is rented AS IS and must be returned to us at the end of the Rental Period in the same condition as when rented. If you rent a child safety seat, you must inspect and install the child seat into the Vehicle yourself. If you rent a navigational system, you should review the operational instructions before leaving the rental location."
  },
  {
    "title": "Insurance; Handling Accidents/Incidents",
    "body": "You are responsible for all damage or loss you cause to others. You agree to provide automobile liability, collision and comprehensive insurance covering you, us, and the Vehicle. Where state law requires us to provide auto liability insurance, or if you have no auto liability insurance, we provide auto liability insurance (the \"Policy\") that is excess to any other valid and collectible insurance whether primary, secondary, excess or contingent. The Policy provides bodily injury liability coverage and property damage liability coverage with limits no higher than minimum levels prescribed by the financial responsibility laws of the State whose laws apply to the loss. The Policy does not cover injury to you. You and we reject PIP, medical payments, no-fault and uninsured and under-insured motorist coverage to the extent permitted by law. To the extent such protection is imposed by operation of law, that protection will be for the minimum limits required by law. You must: (a) report all damage to us and all accidents to us and the police as soon as you discover them and complete our incident report form; and (b) provide us with a legible copy of any service of process, pleading, or notice of any kind related to an accident or other incident involving the Vehicle. Coverage under the Policy is void if you give the Vehicle to an unauthorized driver or otherwise materially breach this Agreement; or if you fail to cooperate in a loss investigation or to file a timely and accurate incident report."
  },
  {
    "title": "Payment; Charges",
    "body": "You permit us to reserve against your payment card (\"Reserve\") or take a cash deposit (\"Deposit\") at the time of rental a reasonable amount in addition to the estimated charges. We may use the Reserve or Deposit to pay all Charges, but will not use the Reserve or Deposit to pay for damage to the Vehicle for which you may be responsible unless you agree separately to allow it after the amount of damage is determined. We will authorize the release of any excess Reserve or refund any excess Deposit after the completion of your rental. Your payment card issuer's rules will apply to your account being credited for the excess and it may not be immediately released by your card issuer. You will pay us at or before conclusion of this rental or on demand all Charges, including: (a) time and mileage for the Rental Period, or a mileage charge based on our experience if the odometer is tampered with; (b) optional products and services you purchased; (c) fuel and a refueling fee, if you return the Vehicle with less fuel than when rented (unless you purchase a prepaid fuel option); (d) Additional Mandatory Charges; (e) all expenses we incur locating and recovering the Vehicle if you fail to return it or if we repossess it under the terms of this Agreement; (f) all costs including pre- and post-judgment attorney fees we incur collecting payment from you or otherwise enforcing or defending our rights under this Agreement; (g) a 2% per month late payment fee, or the maximum amount allowed by law, on all amounts past due; (h) $50, or the maximum amount permitted by law, if you pay us with a check returned unpaid; (i) a reasonable fee to clean the Vehicle if returned substantially less clean than when rented or if the Vehicle contains evidence of smoking; (j) towing, storage charges, forfeitures, court costs, penalties, and all other costs we incur resulting from your use of the Vehicle; (k) a reasonable fee if you lose the keys or toll transponder to the Vehicle; (l) replacement cost of lost or damaged parts and supplies used in Optional Equipment; (m) a reasonable fee if a navigational system that you rented is lost, stolen or otherwise rendered unusable during the rental; and (n) a surcharge if you return the Vehicle to a location other than the location where you rented the Vehicle or if you return it after the date and time due (\"Due-In Date\"). If you return the Vehicle earlier or later than the Due-In Date, a different or higher rate may apply, which may be substantially higher than the rates for the initially agreed rental period if a special or promotional rate applied to the initially agreed rental period. All Charges are subject to a final audit. If errors are found, you authorize us to correct the Charges with your payment card issuer."
  },
  {
    "title": "Responsibility for Tolls, Traffic Violations, and Other Charges",
    "body": "You are liable for all tolls (\"Tolls\") and parking citations, photo enforcement fees, fines for toll evasion, and other fines, fees, and penalties (each a \"Violation\") assessed against you, us or the Vehicle during the Rental Period. If we are notified by charging authorities that we may be responsible for payment of a Toll or Violation, you agree that we or a processing firm (\"Processor\") may, in our sole discretion and without prior notice to you, pay the Toll or Violation plus applicable taxes on your behalf directly to the appropriate authority. If we or a Processor elect to pay a Toll or Violation, you may not be able to challenge the validity of the Toll or Violation before the charging authority. We or the Processor will charge you the face value of the Toll or Violation and any taxes, plus an administrative fee per Toll and Violation. If we or a Processor, in our sole discretion, elect to transfer liability for a Toll or Violation assessed against the Vehicle during the Rental Period to you personally, we or the Processor will charge you an administrative fee per Toll or Violation. You authorize us to release your rental and payment card information to the charging authorities and the Processor for processing and billing purposes. If we or the Processor pay a Toll or Violation, you authorize us and the Processor to charge all payments and administrative fees to the payment card you used in connection with this Agreement. Certain toll roads do not accept cash. To avoid toll violations and associated fines, fees, and taxes (and our administrative fees), you must pay all tolls with a personal transponder that is accepted on the road; use only cash lanes and pay cash; plan a route to avoid tolls; or consult local authorities for other payment methods."
  },
  {
    "title": "Personal Information; Communications",
    "body": "You agree that we may disclose personally identifiable information about you to law enforcement agencies or to other third parties in connection with our enforcement of our rights under this Agreement and for other legitimate purposes. Questions regarding privacy should be directed to the location where you rented the Vehicle. To service your account or recover amounts you owe, you agree that we or our assignee may contact you by calling or sending text messages or emails to any email address or telephone number you provide us, including wireless telephone numbers, which could result in additional charges to you. You represent that you are either the owner or primary user of the number(s) and email address you provided. Methods of contact may include pre-recorded/artificial voice messages and/or use of an automatic dialing device. You may revoke your consent to this contact or to these types of communication at any time by contacting us in writing at the address on the Rental Agreement."
  },
  {
    "title": "Telematics Notice",
    "body": "The Vehicle may be equipped with global positioning satellite (GPS) technology or another telematics system, and/or an event data recorder (EDR). You acknowledge and authorize that your use of this Vehicle may be remotely monitored by us or on behalf of us through such systems to the extent permitted by California law. This remote monitoring may include collection of Vehicle data, such as: location, odometer, oil life, fuel level, tire pressure, battery state of charge, diagnostic trouble codes, and other elements we may deem necessary. These systems may use cellular communications, and you should have no expectation of privacy related to your use of this Vehicle. You agree to inform all drivers and passengers of the Vehicle of the terms of this section, and that you have authorized release of information collected by GPS or other telematics system or EDR. We are not responsible for the operability of any telematics navigational or other system included with the Vehicle. To the extent permitted by law, you agree to indemnify, defend and hold us harmless from any damage to persons or property caused by failure of the GPS or other telematics system or EDR to operate properly, or otherwise arising from the use of the GPS or other telematics system or EDR."
  },
  {
    "title": "Personal Property",
    "body": "We are not responsible for loss of or damage to personal property that was left with us or carried in or on the Vehicle. If you fail to claim property left in the Vehicle for more than 30 days, we may dispose of that property in a manner we choose. To the extent permitted by law, you waive all claims against us, our agents and employees for loss of or damage to the personal property of you or another person, which we received, handled, or stored, or which was left or carried in or on the Vehicle or in any service vehicle or in our offices, whether or not the loss of damage was caused by our negligence or was otherwise our responsibility. The Vehicle may be equipped with an infotainment system that permits you to pair your own mobile devices, and which may download your personal contacts, communications, location or other digital data. You should wipe all personal information from the Vehicle's systems before returning it."
  },
  {
    "title": "Miscellaneous",
    "body": "No term of this Agreement can be waived or modified except by a writing that we have signed. This Agreement constitutes the entire agreement between you and us. All prior representations and agreements between you and us regarding this rental are void. A waiver by us of any breach of this Agreement is not a waiver of any additional breach or waiver of the performance of your obligations under this Agreement. Our acceptance of payment from you or our failure, refusal or neglect to exercise any of our rights under this Agreement does not constitute a waiver of any other provision of this Agreement. To the extent permitted by law: (a) you waive all recourse against us for any criminal reports or prosecutions that we take against you that arise out of your breach of this Agreement; and (b) we will not be liable for consequential, special or punitive damages in connection with this rental or the reservation of a vehicle. If any provision of this Agreement is deemed void or unenforceable, the remaining provisions are valid and enforceable."
  }
]
$cmr_terms$::jsonb
where is_default = true;
